spring:
  application:
    name: supernova-test

  datasource:
    username: postgresuser12
    password: postgresuser12
    url: jdbc:postgresql://skcc-tools-aihack25-postgres.postgres.database.azure.com:5432/postgresdb12
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1024
      minimum-idle: 512
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
